### ISSUE TITLE
HPP/hpp-spline Vs SoT/parametric-curves

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/parametric-curves#12]
Hi,

This lib is a fork from stonneau/spline, which has since become https://github.com/humanoid-path-planner/hpp-spline

Is there any reason to keep both ?

**Comment by olivier-stasse** [comment]
The fork comes from @proyan he is probably the best to explain the differences.

**Comment by proyan** [comment]
Last year when I used @stonneau's spline package to create parametric-curves, I made mostly cosmetic changes in the repository. The main differences in the two repositories are
1) using hpp instead of h headers,
2) renaming curve_abc-> AbstractCurve and other cpp type namings.
3) constant, linear-chirp, infinite-sinusoid, constant trajectories from tsid are imported in parametric-curves
4) Bezier and bernstein curves are not properly imported in paramteric-curves.

I realize that hpp-spline needs the same cosmetic changes that I did for parametric-curves. On the other hand, some of the files are not yet completely imported in parametric-curves.

Both repositories haven't diverged much in content, and reflect the same work. Python bindings need refactoring in both the repositories. Also, both need a code review from other members of the team. 

I would be in favor of using parametric-curves, since the cosmetic changes still need to be done in hpp-spline, and they are partly done in parametric-curves.

However, at the risk of delegating something which was delegated to me, @stonneau's input for the same would be welcome, since both repositories are forked from his original work.

**Comment by nmansard** [comment]
Could you please be more specific about:
3a. are you saying that you created new classes for constant, linear chirp and sinusoid in your parametric-curve repo? 
3b. What is the relation with TSID (beside the fact that you use you parametric-curves in a joint project with TSID)?
4. Are you saying that @stonneau added Bernstein and Bezier to his hpp-spline that you do not have in parametric-curve?

**Comment by stonneau** [comment]
4. Bezier curves were already here before, but indeed from what I remember the unit tests on parametric-curve did not pass for them.
However, a lot has been added to Bezier curve (De Casteljau decomposition in particular).

From my point of view, the easiest way to proceed is to add constant, linear-chirp, infinite-sinusoid to the project after a name refactoring has been made. Ideally, the related commits are isolated in parametric-curves are isolated this should be trivial.

The other way around does not seem relevant, because existing code does not work in parametric-curves.

This thus involves to do a name refactoring in hpp-spline first

**Comment by stonneau** [comment]
This is also based on the fact that based on other reviews, the names might change again anyways

**Comment by stonneau** [comment]
Additionaly I don't agree that the changes are cosmetic (at all).
For instance the behavior is clearly changed in this commit:

https://github.com/stack-of-tasks/parametric-curves/commit/cbe80d381d852a7055b6c9c172a095d6eaf2e216

The subtraction by t_min has disappeared, and clearly the expected output is not the same anymore.

Plus in terms of the api, taking references to double values is a bad idea.

Similarly here the behaviour of the class is not the same anymore. 
We go from a cubic to a "generic" spline, which is not the same behaviour anymore, and must be discussed.

We need to clearly list all the features added in parametric-curves that affect previous behaviours, and decide whether they are relevant or not.

**Comment by proyan** [comment]
> Could you please be more specific about:
> 3a. are you saying that you created new classes for constant, linear chirp and sinusoid in your parametric-curve repo?

Yes. These are defined as classes with the same base class AbstractCurve.

> 3b. What is the relation with TSID (beside the fact that you use you parametric-curves in a joint project with TSID)?

TSID also defined a set of curves. The idea was to use the spline representation and create a repository to be used as the basis for other projects.
> 4. Are you saying that @stonneau added Bernstein and Bezier to his hpp-spline that you do not have in parametric-curve?

Yes. They are not ported into parametric-curves. I only added the piecewise polynomials.

>Additionaly I don't agree that the changes are cosmetic (at all).
For instance the behavior is clearly changed in this commit: cbe80d3

The change is needed in order to have the same representation of f(t) for all classes. However, while this change was big in terms of API, in terms of implementation it was still trivial. With respect to the other commits, code review is definitely needed on this repo.

>From my point of view, the easiest way to proceed is to add constant, linear-chirp, infinite-sinusoid to the project after a name refactoring has been made. Ideally, the related commits are isolated in parametric-curves are isolated this should be trivial.

I'm okay with that. Whichever way requires the least amount of work

**Comment by nmansard** [comment]
Thanks. So let's mark parametric curves as deprecated, and work on a version 2 of hpp-splines where the new curves introduced in parametric curves are ported.

@proyan who is using parametric-curves currently (which projects)? Could you propagate the deprecation info there?

**Comment by proyan** [comment]
On robotpkg, I found a dependency only on sot-torque-control. Once we have replicated the simpler curves in hpp-spline, it should be easy to remove parametric curves completely.
I'll put an issue on sot-torque-control

**Comment by nim65s** [comment]
http://rainboard.laas.fr/project/parametric-curves/robotpkg also says that only sot-torque-control depends on it
